### ISSUE TITLE
No connection to homebridge ..

### ISSUE THREAD

**Issue by coliflower** [SphtKr/homebridge-itunes#12]
Hi,

after installing homebridge-itunes on my MBP, I immediate lost the connection of my App (EVE) to the homebridge server + the CPU increases to 99,7%.

Is there any hint how to solve this topic, please ?

Thanks in advance e!!

**Comment by lzilioli** [comment]
@coliflower 
Sounds like you're experiencing the issue from #5 which has been merged to master but not included in a release.

Until it is released, I got around the issue by installing a specific commit hash from the repo:

`npm install -g SphtKr/homebridge-itunes#a85992c38202f8e5c66932f1ad51ed7dc6241348`

**Comment by coliflower** [comment]
@lzilioli 
Thanks, it helps to solve the 100% CPU issue :-)

What I have now are some error-messages:

> [2016-08-01 20:39:54] [homebridge-itunes.iTunes] [Error: 34:46: execution error: Es ist ein Fehler „-10810“ aufgetreten. (-10810)
> ]
> [2016-08-01 20:39:54] [homebridge-itunes.iTunes] [Error: 35:47: execution error: Es ist ein Fehler „-10810“ aufgetreten. (-10810)
> ]
> [2016-08-01 20:39:54] [homebridge-itunes.iTunes] ERROR: Failed syncing iTunes main device, trying again in two seconds.

Do they need a new issue or do they fit here, too ?

**Comment by lzilioli** [comment]
I'm not sure how to resolve these since I'm not the project maintainer. I didn't run into these issues when I was setting up. Either way, it would probably be good to close out this issue and open a new one mentioning that you're installing a particular commit hash.

**Comment by coliflower** [comment]
OK, thanks a lot !

**Comment by socialsti** [comment]
@coliflower How did you fix the error?

**Comment by coliflower** [comment]
In my case, I recognized to start iTunes before the homebridge starts.
