### ISSUE TITLE
Can't start Homebridge after installing the plugin

### ISSUE THREAD

**Issue by allistoncarlos** [SphtKr/homebridge-itunes#28]
I've installed your plugin right after installing Homebridge. I could initialize the server, but after installing the plugin, I couldn't anymore. The log shows me the following error (I'm using it on Mac OS Sierra 10.12.3, running with launchd):

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn osascript ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

**Comment by ghost** [comment]
@allistoncarlos You need to delete the persist and accessories folder before starting homebridge again.

**Comment by allistoncarlos** [comment]
@misanthrophy Sorry, I forgot to write that I had already deleted the accessories folder. I tried to delete persist too, and got the same error.

**Comment by SphtKr** [comment]
Okay, that error's a little different... Somewhat surprisingly, someone reported this issue against Homebridge itself: nfarina/homebridge#621, but I'm unclear from that discussion what their resolution was.

I think one cause of this can be that the `osascript` command is not found in the PATH. You said you're running via launchd...do you have a PATH declared in your launchd script? It does _not_ get your normal shell's path automatically. For instance, here's what's in my LaunchAgent:

    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/usr/local/bin/:/usr/bin:$PATH</string>
        <key>DEBUG</key>
        <string>ZWayServer,FileSensorAccessory</string>
    </dict>

Also note, if you're trying to run this as a LaunchAgent _and_ as root, you probably will not succeed...it will need to run as a user that can launch iTunes in a GUI session, and that means that the user has to be logged into the GUI console.

**Comment by allistoncarlos** [comment]
That's great, that way worked! Thank you @SphtKr, the LaunchAgent file is now correct!
