### ISSUE TITLE
This plugin breaks other plugins

### ISSUE THREAD

**Issue by ebaauw** [SphtKr/homebridge-itunes#40]
See https://github.com/ebaauw/homebridge-hue/issues/95#issuecomment-295367523.

**Comment by jojost1** [comment]
Thanks @ebaauw, was just about to open a new issue here:

Hi @SphtKr:

This plugin breaks one of my other plugins, [homebridge-hue](https://github.com/ebaauw/homebridge-hue). The dev of that plugin says:
> They override Characteristic.prototype.updateValue(), which is scary at best. To make it worse, they break it by failing to return the characteristic for chaining. homebridge-hue tries to register an event handler on the return value of updateValue(), which now is undefined and no longer contains a property (method) on.

Could you have a look? Maybe you can fix it, would be great! :-)
https://github.com/ebaauw/homebridge-hue/issues/95

**Comment by jojost1** [comment]
@SphtKr Could you take a look?

**Comment by jojost1** [comment]
Since @SphtKr is not responding, do you think this could be an easy fix @ebaauw?

**Comment by ebaauw** [comment]
I don't know why they override Characteristic.prototype.updateValue().

I think your safest option is to run homebridge-itunes in a separate homebridge instance.

**Comment by SphtKr** [comment]
Hey guys, just saw this. Will look into it as soon as I can, but that will probably be a few days yet, sorry... if this is the issue it should be simple enough to resolve, either by returning the characteristic as he suggests or changing the method name I'm using.

**Comment by ebaauw** [comment]
Thanks, @SphtKr.  I think you'd better use another name for your method.  Some-one else might rely on the callback in the original implementation.

**Comment by jojost1** [comment]
Thanks a lot @SphtKr! :)

**Comment by jojost1** [comment]
New commit, so should be fixed now? How can I update to the new version? Thanks a lot :)

**Comment by jojost1** [comment]
Sorry to nag this much @SphtKr, but could you merge this commit?

**Comment by nicknicknickos** [comment]
Pinging @SphtKr - is there any progress towards adding this to a new commit?
