### ISSUE TITLE
Cant get this to run with iTunes 12.4.0

### ISSUE THREAD

**Issue by ghost** [SphtKr/homebridge-itunes#6]
When this plug-in is installed (I'm also using the WeMo and Nest plugins) with latest version of node, NPM, homebridge, etc... then homebridge loads accessories for WeMo and Nest but fails to display the HomeKit pairing code. If I uninstall this plugin then homebridge fires up the other accessories and works.

Is this a known issue?

**Comment by jer78** [comment]
I can confirm it works on iTunes 12.4. There must be something else going on. Can you paste your config file?

**Comment by ghost** [comment]
Sure, I removed some of the values but left the structure intact. If I remove the iTunes platform it works

{
    "bridge": {
        "name": "Homebridge",
        "username": "DC:22:3D:E3:DE:99",
        "port": 51826,
        "pin": "154-56-032"
    },
    "platforms": [
        {
            "platform" : "iTunes",
        },
        {
            "platform" : "Nest",
            "token" : "",
            "clientId" : "",
            "clientSecret" : "",
            "code" : "",
            "username" : "",
            "password" : ""
        }
    ],
    "accessories": [
       {
           "accessory": "WeMo",
           "name": "Salon Heating 1",
           "description": "The heating in the salon",
           "wemo_name": "Salon Heating 1"
       },
       {
           "accessory": "WeMo",
           "name": "Salon Heating 2",
           "description": "The heating in the salon",
           "wemo_name": "Salon Heating 2"
       },
       {
           "accessory": "WeMo",
           "name": "Office Heating",
           "description": "The heating in my office",
           "wemo_name": "Office Heating"
       }
    ]
}

**Comment by jer78** [comment]
Hmm. It looks alright to me. I wonder if I'm using an older version of the plugin. I know the developer was making some recent changes and that might have broken something.

**Comment by ghost** [comment]
Dunno if it helps but I'm using node v6.2.0, npm 3.9.5, homebidge 0.3.4, homebridge-itunes 0.1.1, homebridge-nest 1.1.2, and homebridge-wemo 0.0.2

**Comment by BUMPRW** [comment]
I am having the same issue.  I am running Fedora 23 with node 4.4.5, npm 2.15.5, and node-gyp 3.3.1 on a QNAP TS253-pro using Virtualization Station.  As soon as I delete the module and the input in config.json all runs fine.  I tried it twice.  There were no problems when I loaded the module.  Problem occurred when I attempted to start homebridge.

**Comment by jngothia** [comment]
Same issue, running iTunes 12.4.1, Node 4.4.5, and NPM 3.9.3.  Also running WeMo and Harmony modules.  I can start Homebridge fine if I remove the iTunes module from the config file. 

When I start Homebridge with the iTunes module, I get this error:

/usr/local/lib/node_modules/homebridge-itunes/node_modules/applescript/lib/applescript-parser.js:115
  var rtn = this.value.substring(this.index, end-1);
                       ^

TypeError: this.value.substring is not a function
    at Object.exports.UndefinedParser (/usr/local/lib/node_modules/homebridge-itunes/node_modules/applescript/lib/applescript-parser.js:115:24)
    at Object.parseFromFirstRemaining (/usr/local/lib/node_modules/homebridge-itunes/node_modules/applescript/lib/applescript-parser.js:44:34)
    at Object.exports.parse (/usr/local/lib/node_modules/homebridge-itunes/node_modules/applescript/lib/applescript-parser.js:10:37)
    at ITunesPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-itunes/index.js:443:31)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-itunes/node_modules/node-osascript/lib/index.js:49:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by jer78** [comment]
I don't think iTunes is the problem since I'm on 12.4.1 but also had no issues on 12.4.0. I am on older versions of NPM and Node. 

NPM 3.8.2
Homebridge 0.3.4
Node 5.1.1

**Comment by ghost** [comment]
I'd like to try with older versions of NPM &/or Node but don;t know how to downgrade. Can anyone advise please?

**Comment by JayShallcrass** [comment]
am having the same issue as you @jngothia, have you managed to make any progress?

**Comment by BUMPRW** [comment]
I can put as many versions as I care to on my system, but I don’t which operating system you are using.  I have shifted between 0.8, 0.12.??, 4.4.4, and 6.2 to find which works with homebridge.  I am running Fedora 23 Linux on Virtualization Station on a QNAP TS-253PRO and I am currently running node 4.4.5.  I’ve had no problem running Node and NPM between the different versions, but I couldn’t get the node-gyp module to build under versions 6.2 and 0.8.  Node-gyp is critical to building homebridge modules.

**Comment by SphtKr** [comment]
Hey folks, sorry for being absent. I can now upgrade my node because I had [this blocker](https://github.com/SphtKr/homebridge-zway/issues/14). However, two notes:
1. If it is in fact a node version issue, this won't be a quick fix, because that error originates in a library I depend on :-/. I'll either have to fix the upstream library or change dependencies.
2. This isn't going to work on Linux of any kind, I'm pretty sure, because it requires iTunes to be running on the same system as Homebridge and requires the `osascript` command line utility. So the QNAP won't work. There's a remote (ha!) possibility of doing SSH command based support at some point. Actually, if someone wanted to get really fancy, they could make a `osascript` command script on their linux box that proxied all commands and their results via SSH calls. That would probably be pretty slow though.

**Comment by BUMPRW** [comment]
Okay have tried it on a MacBookPro 2011 and MiniMac 2012 both running OS 10.11.5 and iTunes 12.4.1 and have had no success.

**Comment by jngothia** [comment]
Thanks @SphtKr for the update.

And @JayShallcrass, I unfortunately wasn't able to make any progress using homebridge-itunes.  I instead installed homebridge-ifttt and, through a rather kludgy setup, I can now use IFTTT to make Dropbox files which trigger Applescripts (had to write those myself) on my homebridge server (an always-on Mac), which allows me to control iTunes, AirPlay speakers, volume, and a track skipper all inspired by SphtKr.  There's obviously a rather noticeable lag doing it this roundabout way, but it works.

**Comment by BUMPRW** [comment]
I have to do more experimentation on my Macs, since it may have been working and I was to ignorant to realize it.  I have always seen a read out on my Harmony remote following homebridge start-up and that didn’t happen.  I saw your album skipper at the top when I looked at Eve which automatically added it, but I had been a bit too hasty in removing it from my Mini by the time I looked at Eve.   It appeared to have failed on my MACBOOK PRO but that was days ago and I don’t remember the circumstances.  I was playing with homebridge-server at the time and that may have been a conflict.

**Comment by SphtKr** [comment]
@BUMPRW what version of Node are you using on the macs?

**Comment by BUMPRW** [comment]
On the MACBOOK PRO 4.43 and on the Mini 4.4.5.  I did try it again last night and it locked up homebridge on the mini-mac.  Realize that doesn’t help, I should have copied down the errors, but it was late.

**Comment by Oggymator** [comment]
anybody solve this problem?
